env_name: mampc
algorithm_name: mampc
experiment_name: check
seed: 0
run_dir: ./runs
num_env_steps: 150000000
episode_length: 8
n_rollout_threads: 80
n_eval_rollout_threads: 1
hidden_size: 512
mpc_hidden: 64

use_render: False
recurrent_N: 1
use_single_network: False

save_interval: 1
use_eval: False
eval_interval: 25
log_interval: 25
eval_episodes: 10000

gamma: 0.96
gae_lambda: 0.95
use_gae: True
use_popart: True
use_valuenorm: False
use_proper_time_limits: False

target_kl: 0.016
searching_steps: 10
accept_ratio: 0.5
clip_param: 0.2
learning_iters: 5
num_mini_batch: 1
data_chunk_length: 
value_loss_coef: 1
entropy_coef: 0.0
max_grad_norm: 10
huber_delta: 10.0
use_recurrent_policy: False
use_naive_recurrent_policy: False
use_max_grad_norm: True
use_clipped_value_loss: True
use_huber_loss: True
use_value_active_masks: False
use_policy_active_masks: False

actor_lr: 9.e-5
critic_lr: 5.e-3
opti_eps: 1.e-5
weight_decay: 0.0

mpc_episodes: 120
mpc_horizon: 2


gain: 0.01
actor_gain: 0.01
use_orthogonal: True

use_feature_normalization: True
use_ReLU: True
stacked_frames: 1
layer_N: 2

mpc_buffer_size: 100000
buffer_batch: 64

std_x_coef: 1
std_y_coef: 0.5

mamujoco: 
  num_env_steps: 10000000
  episode_length: 1000
  n_rollout_threads: 10
  n_eval_rollout_threads: 10
  hidden_size: 128
  gamma: 0.99
  entropy_coef: 0.01
  max_grad_norm: 10.0
  use_value_active_masks: True
  use_policy_active_masks: True
  data_chunk_length: 10
  use_valuenorm: False
